steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build app1'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app-1'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push Docker Image for app1'
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/kube-assignment-428815/cloud-k8s-repository/app-1'

#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'Delete existing resources'
#  args:
#    - 'delete'
#    - '-f'
#    - 'deployment.yaml'
#    - '--ignore-not-found'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy app1'
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kube-cluster'

options:
  logging: CLOUD_LOGGING_ONLY